# Generated by Django 3.1 on 2020-08-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200816_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-is_featured',)},
        ),
    ]
