# Generated by Django 3.1 on 2020-08-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200816_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('is_featured',)},
        ),
    ]
