# Generated by Django 3.1 on 2020-08-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200821_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-is_featured',)},
        ),
    ]
